# Setup PHP as Language to Use
language: php

# Choose the PHP Version to test
php:
  - '7.1'
  - '7.2'

# Initialization
before_script:
  - composer self-update
  - composer install --no-interaction

# Script Execution
script:
  - ./vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/coveralls -v
